### ISSUE TITLE
ValueError: Target modules [] not found in the base model. Please check the target modules and try again.

### ISSUE THREAD

**Issue by qingyujean** [wp931120/baichuan_sft_lora#1]
Traceback (most recent call last):
  File "sft_lora.py", line 68, in <module>
    model = get_peft_model(model, config)
  File "/usr/lib/python3.8/site-packages/peft-0.4.0.dev0-py3.8.egg/peft/mapping.py", line 122, in get_peft_model
  File "/usr/lib/python3.8/site-packages/peft-0.4.0.dev0-py3.8.egg/peft/peft_model.py", line 798, in __init__
  File "/usr/lib/python3.8/site-packages/peft-0.4.0.dev0-py3.8.egg/peft/peft_model.py", line 106, in __init__
  File "/usr/lib/python3.8/site-packages/peft-0.4.0.dev0-py3.8.egg/peft/tuners/lora.py", line 174, in __init__
  File "/usr/lib/python3.8/site-packages/peft-0.4.0.dev0-py3.8.egg/peft/tuners/lora.py", line 181, in add_adapter
  File "/usr/lib/python3.8/site-packages/peft-0.4.0.dev0-py3.8.egg/peft/tuners/lora.py", line 333, in _find_and_replace
ValueError: Target modules [] not found in the base model. Please check the target modules and try again.

执行sft_lora.py时会报这个错

**Comment by hahazei** [comment]
我也遇到这个报错，是这个函数find_all_linear_names返回为空组数
